[build-system]
requires = ["maturin>=1.4,<2"]
build-backend = "maturin"

[project]
name = "mzpricer"
version = "0.1.0"
requires-python = ">=3.8"

[tool.maturin]
bindings = "pyo3"
abi3 = true
module-name = "mzpricer"
strip = true